// Persisted Intelligence Reports archive.
// Reports are generated by the harmonic-assistant edge function and stored
// in localStorage so the user can revisit them later.

export type ReportKind = "daily" | "weekly" | "monthly" | "custom";

export interface SavedReport {
  id: string;
  kind: ReportKind;
  title: string;
  createdAt: number;
  body: string;
  /** Snapshot of the analysis context at generation time. */
  context?: Record<string, unknown>;
}

const KEY = "gaiasphere.harmonics.reports.v1";

function safeLoad(): SavedReport[] {
  try {
    const raw = typeof window !== "undefined" ? window.localStorage.getItem(KEY) : null;
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as SavedReport[]) : [];
  } catch {
    return [];
  }
}

function safeSave(reports: SavedReport[]) {
  try {
    if (typeof window === "undefined") return;
    window.localStorage.setItem(KEY, JSON.stringify(reports.slice(0, 50)));
  } catch {
    /* quota or unavailable storage — silently ignore */
  }
}

export function loadReports(): SavedReport[] {
  return safeLoad().sort((a, b) => b.createdAt - a.createdAt);
}

export function saveReport(report: Omit<SavedReport, "id" | "createdAt">): SavedReport {
  const saved: SavedReport = {
    ...report,
    id: `${report.kind}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
    createdAt: Date.now(),
  };
  const all = [saved, ...safeLoad()];
  safeSave(all);
  return saved;
}

export function deleteReport(id: string) {
  safeSave(safeLoad().filter((r) => r.id !== id));
}

export const REPORT_KIND_LABEL: Record<ReportKind, string> = {
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
  custom: "Custom",
};

export const REPORT_PROMPTS: Record<ReportKind, string> = {
  daily:
    "Generate a daily harmonic intelligence report covering the current selection plus any cross-layer events flagged today. Use the Measured / Statistical / Exploratory tiers. Keep it under 250 words with sections: Conditions, Notable Events, Cross-Layer Notes.",
  weekly:
    "Generate a weekly harmonic intelligence report summarizing dynamics across all loaded layers. Compare planetary, solar, stellar, galactic, and cosmological scales where relevant. Use evidence tiers. Sections: Summary, Layer Highlights, Cross-Layer Patterns, Watchlist.",
  monthly:
    "Generate a monthly harmonic intelligence report. Identify trends and emerging patterns, compare layers, and recommend datasets to investigate next month. Use evidence tiers throughout. Sections: Executive Summary, Trends, Cross-Layer Couplings, Anomalies, Recommendations.",
  custom:
    "Generate a focused intelligence report on the current selection. Explain the dominant pattern, classify the evidence tier, and suggest one cross-layer comparison worth running next.",
};
