import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Sphere, SphereId } from "@/types/spheres";
import { Scan, ChevronDown } from "lucide-react";

interface Props {
  sphere: Sphere;
  accent: string;
}

interface StructureElement {
  name: string;
  description: string;
}

const EARTH_IMPACT: Record<SphereId, string> = {
  geosphere: "Tectonic dynamics drive the carbon cycle by subducting organic sediments into the mantle and releasing CO₂ through volcanic degassing, directly regulating atmospheric composition over geological timescales. Earthquake activity redistributes stress across fault networks, triggering cascading effects on groundwater systems, coastal geomorphology, and atmospheric pressure waves detectable in the ionosphere. Volcanic eruptions inject aerosols into the stratosphere, modulating global temperatures and monsoon patterns for years. Crustal composition determines soil fertility, mineral availability for biological systems, and the distribution of piezoelectric minerals that couple mechanical stress to electromagnetic signals. Mantle convection drives the geodynamo that generates Earth's magnetic field — without it, the magnetosphere would collapse, exposing the biosphere to solar radiation.",

  biosphere: "Photosynthesis converted a reducing atmosphere into an oxygen-rich one, enabling complex life and creating the ozone layer that shields the surface from ultraviolet radiation. Vegetation regulates the water cycle through transpiration, generating up to 40% of terrestrial rainfall and directly influencing cloud formation, albedo, and regional climate patterns. Forest ecosystems sequester atmospheric CO₂ and buffer against rapid climate shifts. Marine phytoplankton produce roughly half of Earth's oxygen and form the base of ocean food webs that drive nutrient cycling across the hydrosphere. Coral reefs, wetlands, and mangrove forests protect coastlines, filter water, and maintain biodiversity reservoirs. Metabolic activity generates detectable electromagnetic signatures and biogenic gases that influence atmospheric chemistry. Through decomposition and soil formation, biological systems continuously reshape the geosphere's surface. Human activity has accelerated biospheric change to rates unprecedented in Earth's history.",

  magnetosphere: "Generated by convective flows of liquid iron in the outer core, this electromagnetic cavity extends tens of thousands of kilometers into space. Without it, the solar wind would strip away the atmosphere over geological time, as occurred on Mars. It deflects charged particles from solar flares and coronal mass ejections that would otherwise ionize the upper atmosphere and destroy the ozone layer. It shapes the ionosphere by funneling particles along field lines into auroral zones, driving electrical currents that couple the two systems. Geomagnetic storms can induce ground-level currents strong enough to disrupt power grids, corrode pipelines, and interfere with satellite communications. Radiation belts trap energetic particles that pose hazards to spacecraft. Geomagnetic field variations influence animal navigation — birds, sea turtles, and cetaceans rely on magnetic sense for migration. It also modulates cosmic ray flux reaching the lower atmosphere, which may influence cloud nucleation and climate variability.",

  ionosphere: "Solar ultraviolet and X-ray radiation ionizes atmospheric gases, creating layered plasma structures (D, E, F regions) whose density varies with solar activity, season, and time of day. This ionized medium reflects and refracts radio waves, enabling long-distance communication but disrupting GPS accuracy and satellite signals during geomagnetic storms. It carries massive electrical currents — equatorial electrojet, auroral electrojets, and Sq current systems — that couple to the magnetosphere above and the ground below through field-aligned currents. These currents generate magnetic field variations detectable at Earth's surface and contribute to electromagnetic induction in the crust and oceans. It forms the upper boundary of the Earth-ionosphere waveguide, within which Schumann resonances at ~7.83 Hz propagate globally. Ionospheric disturbances have been observed preceding major earthquakes, suggesting lithosphere-atmosphere-ionosphere coupling. Total Electron Content (TEC) variations affect atmospheric drag on low-Earth-orbit satellites.",

  noosphere: "Through technology, agriculture, urbanization, and industrial activity, humanity has altered atmospheric composition (CO₂ levels unprecedented in 3 million years), redirected river systems, leveled mountains, and triggered the sixth mass extinction. Digital infrastructure — data centers, submarine cables, satellite constellations — carries information at light speed across the globe, creating patterns of collective behavior visible from space as night lights, electromagnetic emissions, and thermal signatures. Financial markets, supply chains, and governance systems create feedback loops that amplify or dampen resource extraction, pollution, and land use change. Scientific observation networks (seismographs, weather stations, satellite arrays) enable real-time monitoring of all other spheres. Energy consumption generates waste heat detectable in urban heat islands and atmospheric thermal anomalies. Electromagnetic emissions create a radio-frequency environment fundamentally different from the natural background.",

  crystalsphere: "Schumann resonances, generated by lightning discharges exciting the Earth-ionosphere cavity, create global electromagnetic pulses at frequencies (7.83 Hz and harmonics) that correlate with biological rhythms across species. Tidal harmonics driven by lunar and solar gravitational forcing create standing-wave patterns in oceans and atmosphere, organizing energy flow at planetary scales. Crystalline structures of the inner core, mantle minerals, and crustal rocks create piezoelectric transduction zones where mechanical stress converts to electromagnetic signals — a mechanism proposed for some earthquake precursor phenomena. Orbital resonances between planets create long-period gravitational harmonics that modulate solar system dynamics and potentially influence solar activity cycles. The geometric distribution of continents, ocean basins, and mountain ranges reflects deep mantle convection patterns that may exhibit self-organizing harmonic properties.",

  hydrosphere: "Oceans cover 71% of Earth's surface and store over 97% of its water, acting as the planet's primary heat reservoir and climate regulator. Thermohaline circulation transports heat from the tropics to the poles over millennial timescales, while wind-driven surface currents drive regional weather and marine productivity. The hydrological cycle continuously exchanges water between oceans, atmosphere, land, and ice — fueling precipitation, weathering, and erosion. Rivers and groundwater sustain terrestrial ecosystems and agriculture; coastal zones support the majority of human population. Ocean acidification from absorbed CO₂ threatens shell-forming marine life, while warming weakens stratification and circulation. Sea level rise, driven by thermal expansion and ice loss, reshapes coastlines globally.",

  cryosphere: "The cryosphere — sea ice, glaciers, ice sheets, snow cover, and permafrost — regulates Earth's energy balance through its high albedo, reflecting solar radiation back to space. Polar ice caps stabilize atmospheric and oceanic circulation by maintaining steep equator-to-pole temperature gradients. Mountain glaciers feed major river systems supplying freshwater to billions. Permafrost stores roughly twice the carbon currently in the atmosphere as frozen organic matter; thaw releases methane and CO₂, amplifying warming. Sea ice loss reduces albedo and accelerates Arctic warming through ice-albedo feedback. Ice sheet collapse in Greenland and West Antarctica contributes to accelerating sea level rise and disrupts ocean circulation through freshwater pulses.",

  atmosphere: "The atmosphere is the thin gaseous envelope that buffers temperature extremes, distributes heat and moisture, shields the surface from harmful radiation, and supplies the oxygen and CO₂ that drive metabolism and photosynthesis. Tropospheric weather systems redistribute energy from equator to poles and from ocean to land, generating precipitation that sustains terrestrial life. The stratospheric ozone layer absorbs UV-B radiation that would otherwise damage DNA and ecosystems. Greenhouse gases — CO₂, methane, water vapor — trap outgoing infrared radiation and set the equilibrium surface temperature; rapid anthropogenic increases now drive global warming, sea level rise, and intensifying extreme weather. Aerosols scatter sunlight, seed clouds, and exert a partial cooling counterforce with strong regional variability. Atmospheric chemistry couples to the biosphere (oxygen, CO₂, biogenic VOCs), the hydrosphere (evaporation, precipitation), the cryosphere (snow and ice feedback), and the ionosphere (photoionization at its upper boundary).",
};

const ANATOMY_DATA: Record<SphereId, { overview: string; elements: StructureElement[] }> = {
  geosphere: {
    overview: "The solid Earth system — a layered domain of tectonic plates, crustal fracture networks, volcanic systems, subduction zones, and deep mantle plume dynamics. Structure is defined by boundary geometries, stress fields, and compositional heterogeneity.",
    elements: [
      { name: "Tectonic Boundaries", description: "Convergent, divergent, and transform plate margins defining the primary structural geometry of crustal interaction." },
      { name: "Crustal Fracture Networks", description: "Fault systems, rift zones, and shear networks that distribute and concentrate tectonic stress across regional domains." },
      { name: "Volcanic Systems", description: "Magmatic plumbing architecture — chambers, conduits, and surface vents linked to subduction and hotspot dynamics." },
      { name: "Subduction Zones", description: "Descending slab geometries where oceanic crust recycles into the mantle, driving deep seismicity and arc volcanism." },
      { name: "Mantle Plume Regions", description: "Deep thermal anomalies producing hotspot volcanism, lithospheric uplift, and localized heat flow signatures." },
    ],
  },
  biosphere: {
    overview: "The living systems layer — a continuous web of bioregions, ecosystem zones, ocean productivity areas, biodiversity distributions, and migratory corridors. Structure is defined by habitat connectivity, trophic organization, and biogeochemical cycling.",
    elements: [
      { name: "Bioregions", description: "Continental-scale ecological zones defined by climate, vegetation type, and biotic community composition." },
      { name: "Ecosystem Zones", description: "Functional habitat units — forests, grasslands, wetlands, coral reefs — each with distinct energy flow and nutrient cycling." },
      { name: "Ocean Productivity Zones", description: "Upwelling regions, photic zone gradients, and pelagic/benthic coupling areas driving marine biomass production." },
      { name: "Biodiversity Distributions", description: "Species richness gradients, endemism hotspots, and functional diversity patterns across latitudinal and altitudinal ranges." },
      { name: "Migration Corridors", description: "Seasonal movement pathways for terrestrial, marine, and avian species connecting breeding, feeding, and overwintering habitats." },
    ],
  },
  magnetosphere: {
    overview: "The planetary electromagnetic shield — a dynamic cavity shaped by Earth's dipole field interacting with the solar wind. Structure is defined by field topology, boundary surfaces, and trapped particle populations.",
    elements: [
      { name: "Dipole Field Lines", description: "The primary magnetic architecture — closed field lines mapping from pole to pole, defining the inner magnetosphere geometry." },
      { name: "Magnetopause", description: "The pressure-balance boundary where Earth's magnetic field meets the solar wind, defining the dayside extent of the cavity." },
      { name: "Bow Shock", description: "The upstream standing shock wave where supersonic solar wind decelerates and heats before flowing around the magnetosphere." },
      { name: "Magnetotail", description: "The elongated nightside extension of the magnetosphere, containing the plasma sheet and reconnection regions driving substorms." },
      { name: "Radiation Belts", description: "Toroidal zones of trapped energetic particles (Van Allen belts) organized by magnetic field geometry and particle energy." },
      { name: "Solar Wind Interface", description: "The deformation layer where external solar wind pressure compresses, stretches, and reshapes the magnetospheric cavity in real time." },
    ],
  },
  ionosphere: {
    overview: "The charged atmospheric shell — a vertically stratified plasma layer extending from ~60 km to ~1000 km altitude. Structure is defined by electron density profiles, photochemical equilibria, and magnetic field coupling.",
    elements: [
      { name: "D/E/F Layer Stack", description: "Vertically stratified ionization regions with distinct density, composition, and solar-dependence characteristics." },
      { name: "Auroral Belts", description: "Oval-shaped zones of intense particle precipitation around the magnetic poles, driven by magnetospheric dynamics." },
      { name: "Polar Cap Ionization", description: "High-latitude ionization structures driven by solar wind–magnetosphere coupling and open magnetic field lines." },
      { name: "Equatorial Anomaly", description: "The Appleton anomaly — dual crests of enhanced electron density flanking the magnetic equator, driven by E×B drift." },
      { name: "Sporadic-E Patches", description: "Thin, dense ionization layers at ~100 km altitude caused by wind shears concentrating metallic ions." },
    ],
  },
  noosphere: {
    overview: "The collective activity layer — a planetary-scale network of communication, knowledge production, and coordinated human action. Structure is defined by network topology, information flow pathways, and semantic density distributions.",
    elements: [
      { name: "Network Topology", description: "The graph structure of global communications — hub-spoke, mesh, and hierarchical architectures connecting nodes of human activity." },
      { name: "Signal Nodes", description: "Major centers of information generation and routing — data centers, research hubs, media clusters, financial exchanges." },
      { name: "Communication Corridors", description: "High-bandwidth pathways linking continental networks — submarine cables, satellite constellations, fiber trunk lines." },
      { name: "Semantic Density Regions", description: "Areas of concentrated knowledge production — research clusters, university networks, innovation ecosystems." },
      { name: "Infrastructure Activity Zones", description: "Urban-industrial complexes where energy use, transportation, and digital activity produce measurable planetary-scale signals." },
    ],
  },
  hydrosphere: {
    overview: "The planetary water domain — oceans, marginal seas, surface waters, groundwater, and atmospheric moisture. Structure is defined by basin geometry, circulation cells, salinity/temperature stratification, and exchange interfaces.",
    elements: [
      { name: "Ocean Basins", description: "Major basin structures (Pacific, Atlantic, Indian, Arctic, Southern) defined by mid-ocean ridges, trenches, and continental margins." },
      { name: "Thermohaline Conveyor", description: "Global density-driven overturning circulation linking surface and deep waters across all ocean basins on millennial timescales." },
      { name: "Surface Current Systems", description: "Wind-driven gyres, boundary currents (Gulf Stream, Kuroshio), and equatorial counter-currents that redistribute heat regionally." },
      { name: "Freshwater Network", description: "Major river systems, lakes, aquifers, and groundwater reserves that sustain terrestrial ecosystems and human use." },
      { name: "Atmospheric Moisture Reservoir", description: "Water vapor and cloud water in the atmosphere — small reservoir, fast turnover, dominant role in weather and climate." },
    ],
  },
  cryosphere: {
    overview: "The frozen planetary domain — sea ice, ice sheets, mountain glaciers, snow cover, and permafrost. Structure is defined by ice mass distribution, grounding lines, calving fronts, and ice-ocean-atmosphere interfaces.",
    elements: [
      { name: "Polar Ice Sheets", description: "Greenland and Antarctic ice sheets — the largest freshwater reservoirs and dominant contributors to long-term sea level change." },
      { name: "Sea Ice Cover", description: "Seasonal and perennial sea ice in Arctic and Southern Oceans regulating albedo, ocean stratification, and polar ecosystems." },
      { name: "Mountain Glacier Systems", description: "Alpine and high-latitude glaciers feeding major river systems and acting as visible indicators of climate change." },
      { name: "Permafrost Zones", description: "Perennially frozen ground across Arctic and sub-Arctic regions storing vast quantities of organic carbon as methane and CO₂." },
      { name: "Seasonal Snow Cover", description: "Northern Hemisphere snowpack — the most variable component of the cryosphere, modulating spring runoff and surface energy budget." },
    ],
  },
  atmosphere: {
    overview: "The gaseous envelope — a vertically stratified column of nitrogen, oxygen, water vapor, and trace gases extending from surface to exosphere. Structure is defined by temperature inversions, circulation cells, chemical reservoirs, and exchange interfaces with the surface and space environment.",
    elements: [
      { name: "Tropospheric Weather Layer", description: "Lowest ~12 km hosting convective weather, water cycle, and ~80% of atmospheric mass; bounded above by the tropopause." },
      { name: "Stratospheric Ozone Reservoir", description: "Ozone-rich layer (15–35 km) that absorbs solar UV-B radiation and warms with altitude, stabilizing the column." },
      { name: "Global Circulation Cells", description: "Hadley, Ferrel, and Polar cells driving meridional heat and moisture transport, modulated by jet streams and Rossby waves." },
      { name: "Greenhouse Gas Reservoir", description: "Long-lived CO₂, CH₄, N₂O and short-lived H₂O vapor regulating the planetary radiative balance." },
      { name: "Aerosol & Cloud Field", description: "Particulate matter and condensed water modulating albedo, precipitation, and atmospheric chemistry." },
    ],
  },
  crystalsphere: {
    overview: "The harmonic resonance layer — a modeled domain representing crystalline lattice structures, standing-wave geometries, and frequency-coherent spatial organization across the planetary system.",
    elements: [
      { name: "Resonance Lattice", description: "Geometric frameworks derived from planetary harmonic relationships — Schumann modes, tidal harmonics, and orbital resonances." },
      { name: "Nodal Grid", description: "Intersection points of standing-wave patterns where constructive interference produces coherence maxima." },
      { name: "Standing-Wave Organization", description: "Spatially fixed wave patterns arising from cavity resonances in the Earth-ionosphere system and solid-body oscillations." },
      { name: "Harmonic Symmetry Scaffolds", description: "Higher-order geometric structures (icosahedral, tetrahedral) reflecting symmetry relationships in planetary field organization." },
      { name: "Piezoelectric Transduction Zones", description: "Regions where crystalline mineral structures convert between mechanical stress and electromagnetic signals." },
    ],
  },
};

export function AnatomyPanel({ sphere, accent }: Props) {
  const anatomy = ANATOMY_DATA[sphere.id];
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="space-y-4">
      {/* Header */}
      <Card className="glass-panel rounded-xl p-5">
        <div className="flex items-center gap-4">
          <div className="w-12 h-12 rounded-xl flex items-center justify-center" style={{ backgroundColor: `${accent}12` }}>
            <Scan className="w-6 h-6" style={{ color: accent }} />
          </div>
          <div className="flex-1">
            <h2 className="text-base font-semibold tracking-wide">Anatomy — {sphere.name}</h2>
            <p className="text-[9px] uppercase tracking-[0.12em] text-muted-foreground/40 mt-0.5">
              Structural model · Domain architecture · System elements
            </p>
          </div>
        </div>
      </Card>

      {/* Overview with expandable Earth Impact */}
      <Card className="glass-panel rounded-xl p-5 space-y-3">
        <h3 className="text-sm font-semibold">Structural Overview</h3>
        <p className="text-xs text-muted-foreground/60 leading-relaxed">{anatomy.overview}</p>
        
        <button
          onClick={() => setExpanded(!expanded)}
          className="flex items-center gap-2 w-full pt-2 border-t border-border/10 transition-all duration-300 group"
        >
          <div className="flex-1 text-left">
            <span className="text-[10px] font-semibold uppercase tracking-[0.15em] text-foreground/60 group-hover:text-foreground/80 transition-colors">
              Earth System Impact
            </span>
          </div>
          <ChevronDown
            className={`w-4 h-4 text-muted-foreground/40 transition-transform duration-300 ${expanded ? "rotate-180" : ""}`}
          />
        </button>

        <div
          className={`overflow-hidden transition-all duration-500 ease-in-out ${expanded ? "max-h-[800px] opacity-100" : "max-h-0 opacity-0"}`}
        >
          <div className="pt-2 pb-1">
            <p className="text-[11px] text-muted-foreground/55 leading-[1.7]">
              {EARTH_IMPACT[sphere.id]}
            </p>
          </div>
        </div>
      </Card>

      {/* Structural Elements */}
      <div className="space-y-3">
        {anatomy.elements.map((el, idx) => (
          <Card key={idx} className="glass-panel rounded-xl p-4">
            <div className="flex items-start gap-3">
              <div
                className="w-7 h-7 rounded-lg flex items-center justify-center text-[10px] font-bold font-mono shrink-0 mt-0.5"
                style={{ backgroundColor: `${accent}12`, color: accent }}
              >
                {String(idx + 1).padStart(2, "0")}
              </div>
              <div className="flex-1 min-w-0">
                <h4 className="text-sm font-semibold text-foreground/85">{el.name}</h4>
                <p className="text-[11px] text-muted-foreground/50 leading-relaxed mt-1">{el.description}</p>
              </div>
            </div>
          </Card>
        ))}
      </div>
    </div>
  );
}
